name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '0 * * * *'
  # for manual workflow trigger
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  update-readme:
    name: Update Readme with Waka Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          COMMIT_MESSAGE: 'Update waka-readme graph by GitHub Actions'
          ### meta
          API_BASE_URL: https://wakatime.com/api
          ### content
          SHOW_TITLE: true
          BLOCKS: ░▒▓█
          CODE_LANG: haxe
          TIME_RANGE: all_time
          LANG_COUNT: 15
          SHOW_TIME: true
          SHOW_TOTAL: true
          STOP_AT_OTHER: true
          ### commit
          AUTHOR_NAME: Intancote
